Update branding
digicatapult/inteli-demo pull request #1
Opened 2022-01-20 11:24 UTC by danielcooperxyz

Update the branding to match the specified companies.

2022-01-21 11:06 UTC, darrylmorton-digicatapult requested changes

2022-01-24 11:21 UTC, jonmattgray approved these changes

2022-01-24 11:34 UTC, darrylmorton-digicatapult requested changes

2022-01-24 11:34 UTC, darrylmorton-digicatapult commented on src/am/components/Navigation.js
>      color: 'white',
missed this one

2022-01-24 11:34 UTC, darrylmorton-digicatapult commented on src/am/components/Navigation.js
>      color: 'white',
and this one

2022-01-24 11:40 UTC, danielcooperxyz commented on src/am/components/Navigation.js
>      color: 'white',
i have but I didn't set those ones, so that's going to be widening the scope of this PR.

2022-01-24 11:41 UTC, danielcooperxyz commented on src/am/components/Navigation.js
>      color: 'white',
Same here. This is going to be widening the scope of this PR.

2022-01-25 10:15 UTC, darrylmorton-digicatapult approved these changes

2022-01-25 11:37 UTC, mattdean-digicatapult approved these changes

2022-01-25 11:41 UTC, merged