Feature/in 93
digicatapult/inteli-demo pull request #17
Opened 2022-02-11 15:59 UTC by n3op2

#### What
mainly adding a logic for handling and dealing with chain resets as per -> https://digicatapult.atlassian.net/jira/software/projects/IN/boards/115?selectedIssue=IN-93 . However there were a lot noise and decided to do some clean up along the way. However, this means that this PR might become very big, but I'm going to break it down and leave it a TODO list and touch only the elements that are needed for the story

..... to be updated

2022-02-15 08:12 UTC, dblane-digicatapult requested changes

2022-02-15 08:12 UTC, dblane-digicatapult commented on .nvmrc
> +v16.13.2
delete

2022-02-15 08:12 UTC, dblane-digicatapult commented on package.json
> +    "start": "REACT_APP_VITALAM_DEMO_PERSONA=cust react-scripts start",
remove?

2022-02-15 08:12 UTC, dblane-digicatapult commented on package.json
> +    "redux-devtools-extension": "^2.13.9",
devDep?

2022-02-15 08:12 UTC, dblane-digicatapult commented on src/am/components/Orders/AcceptAction.js
> +          },
why not do this on line 44 as well?

2022-02-15 09:09 UTC, n3op2 commented on src/am/components/Orders/AcceptAction.js
> +          },
it was prettier

2022-02-15 09:09 UTC, n3op2 commented on package.json
> +    "redux-devtools-extension": "^2.13.9",
to be fair this can be removed

2022-02-15 09:10 UTC, n3op2 commented on .nvmrc
> +v16.13.2
why? it helps to set my nvm, allows to use `nvm use` command

2022-02-15 09:12 UTC, n3op2 commented on package.json
> +    "redux-devtools-extension": "^2.13.9",
removed

2022-02-15 09:13 UTC, n3op2 commented on package.json
> +    "start": "REACT_APP_VITALAM_DEMO_PERSONA=cust react-scripts start",
done

2022-02-15 09:24 UTC, dblane-digicatapult commented on .nvmrc
> +v16.13.2
We got rid of this previously.
```nvm use $(jq -r .engines.node package.json)```

2022-02-15 09:35 UTC, darrylmorton-digicatapult requested changes

2022-02-15 09:35 UTC, darrylmorton-digicatapult commented on .nvmrc
> +v16.13.2
Not needed at the project level, it's far too granular and dev environment specific. Please remove

2022-02-15 09:35 UTC, darrylmorton-digicatapult commented on .eslintrc
> +    "extends": ["eslint:recommended", "plugin:react/recommended", "prettier"],
Looks like unnecessary diff churn, what has caused this?

2022-02-15 09:39 UTC, n3op2 commented on TODO.md
> +### Might worth discussing but this is what I got so far.
Removed, wanted to remove before promoting this draft to real one.

2022-02-15 15:37 UTC, jonmattgray commented on src/utils/vitalamApi.js
> +    } else {
this check for the empty `` metadata key can be removed and `getNewMetadata` can be called `getMetadata`. It's from when the demo was a mix of old style and new style tokens. All tokens created within the demo are now new style, with metadata keys, so we can use the route `.../item/${token.id}/metadata/${metadata_key}`, as you have on L118

old style tokens didn't set a metadata key so the API would give them a default empty `` key

2022-02-15 15:44 UTC, jonmattgray commented on src/features/networkStatusSlice.js
> +// QUESTION why do we need this?
it gets used to show whether the front end is successfully polling the chain, the WiFi signal icon in the top right of  most (all?) pages updates to show good/bad connection.

Unless you're asking why it needs to be a slice...

2022-02-16 17:32 UTC, darrylmorton-digicatapult requested changes

2022-02-16 17:32 UTC, darrylmorton-digicatapult commented on src/features/tokensSlice.js
> +    return await getData(
await not needed

2022-02-16 17:32 UTC, darrylmorton-digicatapult commented on src/features/tokensSlice.js
> +        ref: isRef ? token : tokens.ref || undefined,
I don't think explicitly setting `undefined` as a value is good practice. Is there a good reason for doing so?

2022-02-16 17:32 UTC, darrylmorton-digicatapult commented on src/redux-middleware/localstorage.js
> +  const existing = localStorage.getItem(key) || undefined
`undefined`?

2022-02-16 17:43 UTC, jonmattgray commented on src/utils/resetChain.js
> +  const roles = { Owner: '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty' } // TODO get correct owner
constants file for identities https://github.com/digicatapult/inteli-demo/blob/main/src/utils/identities.js

2022-02-16 18:22 UTC, n3op2 commented on src/features/tokensSlice.js
> +    return await getData(latestToken, null, last?.id)
this is because I want to return a fulfilled promised rather than a promise. Going to test this out to confirm

2022-02-16 18:23 UTC, n3op2 commented on src/features/tokensSlice.js
> +  const { ORDER, LAB_TEST, POWDER } = groupBy(tokens, 'metadata.type')
saves a few lines, but if people are against having lodash or an extra module, happy to switch to reduce.

2022-02-16 18:23 UTC, n3op2 commented on src/features/tokensSlice.js
> +  if (id === last?.id)
I would do it like `if (!a) return b` but eslint was erroring, will update to include braces

2022-02-16 18:25 UTC, n3op2 commented on src/features/tokensSlice.js
> +        ref: isRef ? token : tokens.ref || undefined,
the main reason for setting undefined here is so when you use spread it removes undefined properties e.g.

```js
const o = {
  a: 'a',
  b: 'b',
  undefined,
}
console.log(o) // will print only a and b
```

2022-02-16 18:27 UTC, n3op2 commented on src/shared/BlockchainWatcher.js
>      let timer = undefined
this was originally there, wanted to get rid of this but it requires a few more changes there and there and I think it makes more sense to have it as a separate story.

2022-02-16 18:29 UTC, n3op2 commented on package.json
> +    "axios": "^0.26.0",
because fetch needs *like* a double promise when in the world of reducers e.g.
```js
fetch(options).then(res => {
  const result = res.json()
  doSomething(result) // result will not get resolved so used axios, might be missing something here? Will review this tomorrow morning
}) 
```

2022-02-17 09:08 UTC, darrylmorton-digicatapult commented on src/shared/BlockchainWatcher.js
>      let timer = undefined
understood, should be `null` instead.

2022-02-17 09:12 UTC, darrylmorton-digicatapult commented on package.json
> +    "axios": "^0.26.0",
Could be that you're missing `await res.json()`

`fetch(options).then(res => {
  const result = await res.json()
  doSomething(result)
}) `

2022-02-17 09:24 UTC, darrylmorton-digicatapult commented on src/features/tokensSlice.js
> +  if (id === last?.id)
Our eslint/prettier could do with updating in the near future to enforce some consistency. It also doesn't help that we don't have tests on the UI so a bit of safeguarding goes a long way, and curly braces can reduce bugs creeping in especially where multiple returns are present

2022-02-17 09:36 UTC, n3op2 commented on src/redux-middleware/localstorage.js
> +  return item ? JSON.parse(item) : null
wrapped inside try/catch also moved to utils.js

2022-02-17 09:37 UTC, n3op2 commented on package.json
> +    "axios": "^0.26.0",
this does not sound right, not sure if you can use await inside `.then` block

2022-02-17 09:38 UTC, n3op2 commented on src/features/tokensSlice.js
> +const getData = async (last = { id: 1 }, tokens = {}, position = undefined) => {
removed as it's going to be undefined anyway...

2022-02-17 09:38 UTC, n3op2 commented on src/redux-middleware/auth.js
> +const auth = (store) => (next) => (action) => { // eslint-disable-line
sotre is not being used and it moans about it... does not allow me to compile

2022-02-17 09:39 UTC, n3op2 commented on src/features/tokensSlice.js
> +  if (id === last?.id)
updated in all places across this PR

2022-02-17 10:57 UTC, n3op2 commented on src/utils/resetChain.js
> +  const roles = { Owner: '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty' } // TODO get correct owner
@n3op2 catch up with jonathan - personal note

2022-02-17 13:31 UTC, n3op2 commented on package.json
> +    "axios": "^0.26.0",
updated to use `fetch` and axios has been removed from `package.json`

2022-02-17 13:32 UTC, n3op2 commented on src/features/tokensSlice.js
> +  const { ORDER, LAB_TEST, POWDER } = groupBy(tokens, 'metadata.type')
updated to use simple `.forEach` as we can do one by one (unfortunately, this action does not take array and updating it might require another story)

2022-02-17 13:32 UTC, n3op2 commented on src/shared/BlockchainWatcher.js
>    useEffect(() => {
removed, added isLoading state as per our discussion

2022-02-17 13:33 UTC, n3op2 commented on src/features/tokensSlice.js
> +  return token.id === 1 || position + 1 === token.id || isRef
updated all of them, well I think that all of them should be covered along with braces for if statements

2022-02-17 14:08 UTC, darrylmorton-digicatapult commented on src/features/networkStatusSlice.js
> +// QUESTION why do we need this?
remove comment

2022-02-17 15:19 UTC, darrylmorton-digicatapult submitted a review, later dismissed

2022-02-17 17:00 UTC, dblane-digicatapult submitted a review, later dismissed

2022-02-17 18:26 UTC, dblane-digicatapult submitted a review, later dismissed

2022-02-22 10:20 UTC, mattdean-digicatapult commented on src/features/tokensSlice.js
> +  initialState: { isFetching: true, isError: false, data: [] },
How is `refToken` initialised?

2022-02-22 10:26 UTC, mattdean-digicatapult commented on src/utils/resetChain.js
> +import tokenTypes from './tokenTypes'
This file doesn't seem to be referenced anywhere; am I missing something? How is the `refToken` actually created

2022-02-22 10:40 UTC, nitro-marky commented on src/features/tokensSlice.js
> +  initialState: { isFetching: true, isError: false, data: [] },
I think `refToken` comes from line 44

2022-02-22 10:54 UTC, n3op2 commented on src/features/tokensSlice.js
> +  initialState: { isFetching: true, isError: false, data: [] },
@mattdean-digicatapult it's not, bascially if it can not find a ref token, then it will fetch tokens all the way up to first one, if there is one, then it will fetch up until latest refToken

2022-02-22 10:56 UTC, n3op2 commented on src/utils/resetChain.js
> +import tokenTypes from './tokenTypes'
So we used in multiple places, I've abstracted it to be as a util rather than everywhere else it was create a new variable, also i think it was using array and checking by the index, might be wrong, but it was repeating across the board, it's being used, please refer to my screenshot:
<img width="763" alt="Screenshot 2022-02-22 at 10 55 23" src="https://user-images.githubusercontent.com/11794402/155118528-ca5cf6d0-aceb-4aa0-b33d-f9be42e06c05.png">

2022-02-22 10:57 UTC, n3op2 commented on src/utils/resetChain.js
> +  const roles = { Owner: '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty' } // TODO get correct owner
Mmm... it's because other identities are hardcoded, need to updated and to import from utils/identities, but there are hardcoded

2022-02-22 11:01 UTC, mattdean-digicatapult commented on src/features/tokensSlice.js
> +  initialState: { isFetching: true, isError: false, data: [] },
I'd recommend explicitly setting `refToken: null` or similar in `initialState` so that it's clear this exists in state.

2022-02-22 11:03 UTC, mattdean-digicatapult commented on src/utils/resetChain.js
> +import tokenTypes from './tokenTypes'
I meant the whole file 😆 @n3op2, but if you want a specific question where is `createRefToken` used?

2022-02-22 11:48 UTC, darrylmorton-digicatapult commented on src/features/partsSlice.js
>    initialState: [
**This could be performed in another ticket:**

To avoid hardcoding the partIds in multiple places, you could pull these parts out from the initialState into their own variable outside of `partsSlice`:
`initialState: parts,`
 
`mapPartIdToImage` could then loop through parts to obtain and set partIds as keys with corresponding image.parts[index] values

2022-02-22 14:40 UTC, jonmattgray commented on src/features/tokensSlice.js
> +  const isRefToken = token.metadata.type === 'REFERENCE'
this could be a new constant in https://github.com/digicatapult/inteli-demo/blob/main/src/utils/tokenTypes.js

2022-02-22 14:49 UTC, danielcooperxyz reviewed
This PR is so big I can't review it in a reasonable amount of time.

Can you make sure that the commit message for the squash merge details both of the tickets, as well as the refactoring that has taken place.

2022-02-22 15:00 UTC, jonmattgray commented on src/utils/vitalamApi.js
> -import { updateNetworkStatus } from '../features/networkStatusSlice'
network status doesn't seem to be updated anywhere now?

2022-02-22 15:03 UTC, n3op2 commented on src/utils/resetChain.js
> +  const roles = { Owner: '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty' } // TODO get correct owner
It has been updated to use as everywhere else in the platform

2022-02-22 15:03 UTC, n3op2 commented on src/features/tokensSlice.js
> +  initialState: { isFetching: true, isError: false, data: [] },
@mattdean-digicatapult updated!

2022-02-22 15:05 UTC, n3op2 commented on src/utils/resetChain.js
> +import tokenTypes from './tokenTypes'
Oh,... sorry thought you were talking about the import, at the moment it's not being used anywhere this is just a handler so we still need to decide whether we want tit to be a button or ... Liam was suggesting something like admin tab, so this is why I left functionality until we agree where and how we would like to use it. @mattdean-digicatapult

2022-02-22 15:13 UTC, n3op2 commented on src/utils/vitalamApi.js
> +  const newWrappedFetch = useNewFetchWrapper()
MMm... I've updated `getNewMetadata` but I would rather not change the `wrappedFetch` as I would like to get this merged also I can see wrappedFetch and wrappedNewFetch are being used, so I will leave it for another story

2022-02-22 15:13 UTC, n3op2 commented on src/utils/vitalamApi.js
> -import { updateNetworkStatus } from '../features/networkStatusSlice'
this was a test! Adding it back:)

2022-02-22 15:15 UTC, n3op2 commented on src/features/tokensSlice.js
> +    if (['ORDER', 'LAB_TEST', 'POWDER'].includes(type)) {
updated, will push shortly

2022-02-22 15:20 UTC, mattdean-digicatapult commented on src/utils/resetChain.js
> +import tokenTypes from './tokenTypes'
right ok

2022-02-22 15:28 UTC, jonmattgray commented on src/features/tokensSlice.js
> +  POWDER: (token, dispatch) => dispatch(upsertPowder(token)),
can be constants

2022-02-22 15:32 UTC, jonmattgray commented on src/features/tokensSlice.js
> +    throw new Error(`there are no tokens to fetch. Latest: ${id}`)
throws an error when latest token is `0` but that's not an error?

2022-02-22 15:35 UTC, jonmattgray commented on src/features/tokensSlice.js
> +    throw new Error(`there are no tokens to fetch. Latest: ${id}`)
also could local storage `state` be auto-cleared if latest token is `0` or some other criteria? Would save us having to clear it in browser whenever we restart the demo

2022-02-22 15:37 UTC, n3op2 commented on src/features/tokensSlice.js
> +    throw new Error(`there are no tokens to fetch. Latest: ${id}`)
it will be logged as warning on line 107

```js
  } catch (e) {
    store.dispatch(updateNetworkStatus(false))
    console.warn('Error occured fetching tokens: ', e)
  }
})
```

2022-02-22 15:42 UTC, n3op2 commented on src/utils/vitalamApi.js
> +  const newWrappedFetch = useNewFetchWrapper()
it's not and I rather leave it for another story, something like clean up...

2022-02-22 15:43 UTC, n3op2 commented on src/features/tokensSlice.js
> +    throw new Error(`there are no tokens to fetch. Latest: ${id}`)
happy to rename to `Warning occured...` I think we should implement a logger, but again another story.

2022-02-22 15:52 UTC, jonmattgray commented on src/features/tokensSlice.js
> +import { Api, tokenTypes } from '../utils'
typo in one of the last commits, `Api` import should be from `../vitalamApi`

2022-02-22 15:58 UTC, jonmattgray commented on src/features/tokensSlice.js
> +    throw new Error(`there are no tokens to fetch. Latest: ${id}`)
isn't it fine if the latest token is `0`?

2022-02-22 16:19 UTC, n3op2 commented on src/features/tokensSlice.js
> +import { Api, tokenTypes } from '../utils'
well it's a default import so it should work, no? also it sees it as a function? Will test that now

2022-02-23 09:52 UTC, darrylmorton-digicatapult approved these changes

2022-02-23 11:40 UTC, danielcooperxyz submitted a review, later dismissed
Is it possible to back out your changes to the auth mechanism? 

Most of the stuff you've changed is going to be redundant and it's pretty far out of scope of this ticket.

2022-02-23 13:37 UTC, merged