Certification list in order token
digicatapult/inteli-demo pull request #18
Opened 2022-02-15 08:11 UTC by jonmattgray

2022-02-15 14:02 UTC, jonmattgray commented on src/shared/BlockchainWatcher.js
> +          if (
this is the refetch hack I mentioned in standup this morning 😿

2022-02-15 14:12 UTC, jonmattgray commented on src/shared/BlockchainWatcher.js
> +          }
any suggestion for if we change the API, or this code could live somewhere else in the demo

2022-02-15 14:17 UTC, dblane-digicatapult commented on src/shared/BlockchainWatcher.js
> +          }
Does the API currently not respect `Accept` header?  If so we should definitely make sure it does.

2022-02-15 14:34 UTC, jonmattgray commented on src/shared/BlockchainWatcher.js
> +          }
I don't think the API has any code for taking into account `Accept`, here's where it sends files https://github.com/digicatapult/vitalam-api/blob/6d8137e9337810a801f4a4c117ffbd6d2ae2cd7d/app/util/appUtil.js#L460

Accept header wouldn't help this problem because the front end would still have to know what `content-type` each metadata file was before requesting it? Ideally the API would have correct headers and the front end interpret each file's data accordingly, I'll have a look now at how easy it would be to have more precise `content-type` from the API based on what gets stored for a file in IPFS

2022-02-15 16:46 UTC, jonmattgray commented on src/shared/BlockchainWatcher.js
> +          }
I'm gonna switch to hardcode

2022-02-15 16:47 UTC, darrylmorton-digicatapult requested changes

2022-02-15 17:52 UTC, jonmattgray commented on src/customer/components/CustomerPart.js
> +    return {
changed

2022-02-15 17:52 UTC, jonmattgray commented on src/shared/BlockchainWatcher.js
> +  return await response.json()
deleted await

2022-02-16 09:53 UTC, nitro-marky commented on src/am/components/Orders/CertificationRow.js
> +            //TODO download/upload
Is that part of this ticket?

2022-02-16 09:58 UTC, jonmattgray commented on src/am/components/Orders/CertificationRow.js
> +            //TODO download/upload
it is, planning on doing it in the next PR. I wanted to stop this one being too big and the upload logic might be confusing so wanted it to be its own PR

2022-02-16 09:59 UTC, darrylmorton-digicatapult approved these changes

2022-02-16 10:12 UTC, nitro-marky commented on src/am/components/Orders/Certification.js
> +        {order.metadata.requiredCerts.map((cert) => {
Will there be a separate certification status for this or is it equivalent to 'manufactured'?

2022-02-16 11:24 UTC, jonmattgray commented on src/am/components/Orders/Certification.js
> +        {order.metadata.requiredCerts.map((cert) => {
I was thinking we don't need one but it's up for discussion, maybe there could be a status like 'certifying' whilst certificates are getting added. The way I've done it so far is the certificate list only shows when status is `accepted`, which is how it is on the design

2022-02-16 11:33 UTC, jonmattgray commented on src/am/components/Orders/Certification.js
> +        {order.metadata.requiredCerts.map((cert) => {
I asked Liam and we want the certificates to show for all statuses from `accepted` onwards, so will make this change now

2022-02-17 09:35 UTC, merged