IN-126 Notify OEM when PO has been rejected by T1
digicatapult/inteli-demo pull request #21
Opened 2022-02-18 11:10 UTC by nitro-marky

This adds a rejection box to the vertical timeline with the proposed details from the T1. The accept button currently works but there is no flow for the rejection process at the moment.

**Before**

<img width="1043" alt="Screenshot 2022-02-18 at 11 08 42" src="https://user-images.githubusercontent.com/35331926/154671779-edbaec6d-3fbd-40c6-99ce-87c14954e0dc.png">

**After**

<img width="1043" alt="Screenshot 2022-02-18 at 11 09 31" src="https://user-images.githubusercontent.com/35331926/154671820-c936c3bf-a729-476e-9e97-2235c5eb71d5.png">

2022-02-18 14:24 UTC, darrylmorton-digicatapult reviewed
You'll need to resolve your conflicts with `main` branch

2022-02-18 16:10 UTC, darrylmorton-digicatapult commented on src/customer/components/AmendedTimelineItem.js
> +            {moment(deliveryBy, 'YYYY-MM-DD').format('DD - MM - YYYY')}
Could you create a variable for this outside the render/return?
Also the parsing date format for `deliveryBy` can be reused via `utils/forms` `DATE_PICKER_DATE_FORMAT`

2022-02-18 16:31 UTC, darrylmorton-digicatapult commented on src/customer/components/VerticalTimeline.js
> +            <TimelineSeparator className={classes.columnMinHeight}>
Is the `className` working here? I thought that's why the `style={{}}` attributes were used instead of `className` on the `TimeLine` elements?

2022-02-21 10:36 UTC, jonmattgray commented on src/customer/components/VerticalTimeline.js
> +                    status === 'amended'
use constant for `amended`

2022-02-21 17:37 UTC, darrylmorton-digicatapult requested changes

2022-02-21 17:37 UTC, darrylmorton-digicatapult commented on src/customer/components/TimelineOrder.js
>                        {status === 'amended'
orderStatus.amended

2022-02-21 17:37 UTC, darrylmorton-digicatapult commented on src/customer/components/TimelineOrderDot.js
> +  console.log(statusIndex, row)
console.log

2022-02-21 17:40 UTC, nitro-marky commented on src/customer/components/TimelineOrder.js
>                        {status === 'amended'
The status should contain whether it is amended or not. It's then up to the component to act accordingly

2022-02-21 17:40 UTC, darrylmorton-digicatapult requested changes

2022-02-21 17:40 UTC, darrylmorton-digicatapult commented on src/customer/components/AmendedTimelineItem.js
> +const AmendedTimeLineItem = ({ order }) => {
This could probably do with renaming to `TimelineAmendedItem`

2022-02-21 17:40 UTC, jonmattgray commented on src/customer/components/TimelineOrder.js
> +  console.log(order)
log

2022-02-21 17:45 UTC, nitro-marky commented on src/customer/components/TimelineOrder.js
>                        {status === 'amended'
Row 2 doesn't always mean amended, it could also mean accepted. We have single process words that represent multiple states

2022-02-21 17:46 UTC, nitro-marky commented on src/customer/components/TimelineOrder.js
>                        {status === 'amended'
Which is a bit 😬

2022-02-21 17:47 UTC, darrylmorton-digicatapult commented on src/customer/components/TimelineOrder.js
>                        {status === 'amended'
`status === 'amended'` is the same as `status === orderStatus.amended` except the latter is not hardcoding and reusing the status from a util?

2022-02-21 18:01 UTC, darrylmorton-digicatapult requested changes

2022-02-21 18:33 UTC, darrylmorton-digicatapult requested changes

2022-02-21 18:33 UTC, darrylmorton-digicatapult commented on src/utils/timeline.js
> +  moment(timestamp).format('DD-MM-YYYY hh:mm')
The time should be 24 hour time format `moment(timestamp).format('DD-MM-YYYY HH:mm')`

2022-02-22 09:14 UTC, darrylmorton-digicatapult approved these changes

2022-02-22 09:30 UTC, danielcooperxyz reviewed
Great to see you refactoring as you go along, although I may not have made the same decisions myself. Can you help me understand your thinking behind the abstraction of the statusLabels array? I presume the getter removes the liklihood of the array being updated unintentionally?

2022-02-22 09:30 UTC, danielcooperxyz commented on src/customer/components/TimelineOrder.js
> +                        : getStatusLabel(1)}
I am in two minds about these indexer values being used like this. Say something to convince me?

2022-02-22 09:30 UTC, danielcooperxyz commented on src/utils/timeline.js
> +  }
this also seems to be conflicting in my mind with the constant values used directly above.

2022-02-22 09:56 UTC, nitro-marky commented on src/customer/components/TimelineOrder.js
> +                        : getStatusLabel(1)}
These index values have been extracted out into helper files and are used to get the correct label for the timeline based on a a condition, in this case 'Order Accepted' or 'Order Negotiated'. By having this method of getting the labels, it means others can be added in the future, if necessary (which is highly likely), without affecting this code. 

I'd be interested to see how you would do something similar.

2022-02-22 09:57 UTC, nitro-marky commented on src/utils/timeline.js
> +  }
These numerical values relate to the row they exist on within the timeline, it simply converts a string value to a numerical row value. Which is why it has ben extracted to a utility file.

2022-02-22 10:04 UTC, darrylmorton-digicatapult commented on src/customer/components/TimelineOrder.js
> +                        : getStatusLabel(1)}
Removing unnecessary hardcoding of values in multiple places, these indexes could be replaced constant/enum solution but I think it's overkill at this stage. The refactoring was based around breaking things down and reuse but had to draw the line somewhere as there's already been a lot of comments/change requests.

2022-02-22 10:04 UTC, darrylmorton-digicatapult commented on src/utils/timeline.js
> +  }
related to previous comment

2022-02-22 10:12 UTC, darrylmorton-digicatapult commented
I think it's time to merge this @nitro-marky.

2022-02-22 10:16 UTC, merged