Use OrderQuantityInput and OrderDeliveryByDatePicker components for OEM
digicatapult/inteli-demo pull request #24
Opened 2022-02-21 13:18 UTC by jonmattgray

2022-02-21 13:59 UTC, jonmattgray commented on src/customer/components/VerticalTimeline.js
> +    moment(timestamp).format('DD-MM-YYYY HH:mm')
design has time in 24H format

2022-02-21 18:28 UTC, darrylmorton-digicatapult commented on src/customer/components/VerticalTimeline.js
> +    moment(timestamp).format('DD-MM-YYYY HH:mm')
good spot but outside the scope of this ticket, will cause conflicts and this file has since been renamed.
will request this change in the other ticket before it's merged.

2022-02-21 18:42 UTC, darrylmorton-digicatapult requested changes

2022-02-21 18:42 UTC, darrylmorton-digicatapult commented on src/shared/OrderQuantityInput.js
> +    width: '150px',
This change will affect the other page that's also using this component, so worth checking...

2022-02-21 18:42 UTC, darrylmorton-digicatapult commented on src/utils/forms.js
> +const isQuantityInvalid = (value, maxValue = Infinity) => {
This change will affect the other page that's also using this component, so worth checking...

2022-02-22 09:48 UTC, jonmattgray commented on src/customer/components/VerticalTimeline.js
> +    moment(timestamp).format('DD-MM-YYYY HH:mm')
changed it back

2022-02-22 10:15 UTC, nitro-marky commented on src/am/components/Orders/Negotiate.js
> +            className={`${classes.rejectAndNegotiateToggle}`}
just needs to be `className={classes.rejectAndNegotiateToggle}`

2022-02-22 10:20 UTC, danielcooperxyz approved these changes

2022-02-22 10:20 UTC, danielcooperxyz commented on src/customer/components/CustomerPart.js
> +    return !isQuantityInvalid(quantity) && !isDeliveryByInvalid(deliveryBy)
does the negation of these make it confusing?

2022-02-22 10:21 UTC, nitro-marky approved these changes

2022-02-22 10:24 UTC, merged

2022-02-22 10:25 UTC, jonmattgray commented on src/am/components/Orders/Negotiate.js
> +            className={`${classes.rejectAndNegotiateToggle}`}
I'll fix it in my next PR since this one is approved (and now merged)

2022-02-22 10:30 UTC, jonmattgray commented on src/customer/components/CustomerPart.js
> +    return !isQuantityInvalid(quantity) && !isDeliveryByInvalid(deliveryBy)
it for sure makes it more confusing than it was before