Add user authentication flow
digicatapult/inteli-demo pull request #26
Opened 2022-02-23 09:30 UTC by danielcooperxyz

Authentication was previously done using machine to machine authentication. These changes enable users to acces the application and authenticate themselves against Auth0, which is then used for token creation against the blockchain API service.

These changes are only for the basic authentication flow to Auth0 to permit access to the web application and API.

2022-02-23 13:30 UTC, mattdean-digicatapult commented on package.json
> +    "envalid": "^7.2.2",
you won't be able to use `envalid` for this as it's frontend only (there is no environment. We will probably shift to pulling config from a `config.json` served by nginx (if you remmeber our discussion the other day @danielcooperxyz) but for now you could continue to use `REACT_APP_` style build time configuration

2022-02-23 13:33 UTC, darrylmorton-digicatapult commented on src/utils/env.js
> +module.exports = { ...vars }
export default {

2022-02-23 13:42 UTC, n3op2 requested changes
I've created

2022-02-23 13:42 UTC, n3op2 commented on src/customer/router/index.js
> +    onRedirecting: () => <h1>Redirecting...</h1>,
maybe render something more aesthetic? even the overlay and spinner would be better than `<h1>` saying redirected

2022-02-23 13:42 UTC, n3op2 commented on src/utils/env.js
> +const envalid = require('envalid')
this got to be in ES6

2022-02-23 13:42 UTC, n3op2 commented on src/utils/env.js
> +module.exports = { ...vars }
this is why module.exports does not work because dialect should be ES6 which is `export`

2022-02-23 13:42 UTC, n3op2 commented on src/utils/vitalamApi.js
> +  const { getAccessTokenSilently } = useAuth0()
I've created a middleware, so please rebase with main

2022-02-23 14:11 UTC, danielcooperxyz commented on src/customer/router/index.js
> +    onRedirecting: () => <h1>Redirecting...</h1>,
out of scope

2022-02-23 14:31 UTC, danielcooperxyz commented on src/index.js
> +    redirectUri={'http://localhost:3000/app/customer-parts'}
resolved, thanks

2022-02-23 14:40 UTC, mattdean-digicatapult commented on src/customer/router/index.js
> +    onRedirecting: () => <h1>Redirecting...</h1>,
agreed, if the PO sees it and asks for a more "pretty" experience that's fine. Otherwise it's likely waste

2022-02-23 15:43 UTC, nitro-marky commented on src/customer/router/index.js
> +    onRedirecting: () => <h1>Redirecting...</h1>,
It would be good to use Typography though instead of H1 tags to keep with general covention.

2022-02-25 08:57 UTC, danielcooperxyz commented on src/index.js
> +    redirectUri={'http://localhost:3000/app/customer-parts'}
I had to use different values to these variables, as these variables are for the API location. I have written some code to get the appropriate values, please have a look and let me know what you think

2022-02-25 09:40 UTC, mattdean-digicatapult requested changes
One very small change

2022-02-25 09:40 UTC, mattdean-digicatapult commented on src/customer/router/index.js
> +    }
Not a big fan of spurious logs in the console like this, especially when we don't have configurablew log levels. For now remove please

2022-02-25 14:05 UTC, darrylmorton-digicatapult approved these changes

2022-02-28 14:43 UTC, closed without merging