quantity and deliveryby validation with error messages, styling, addi…
digicatapult/inteli-demo pull request #3
Opened 2022-01-25 09:07 UTC by darrylmorton-digicatapult

- [x] quantity and deliverBy request params
- [x] validation with error messages
- [x] button enable/disable
- [x] version bump

2022-01-25 14:44 UTC, jonmattgray commented on src/customer/components/CustomerPart.js
> +      formData.append('deliveryBy', deliveryBy)
`quantity` and `deliveryBy` could go in `fileData` for now? Will ultimately change with new token format though

2022-01-26 11:11 UTC, danielcooperxyz reviewed
Great work! It's nice to see the correct usage of hooks for stateful components.

I have a couple of queries relating to some specific logic but on the whole it looks like a useful addition to the codebase.

2022-01-26 11:11 UTC, danielcooperxyz commented on src/customer/components/CustomerPart.js
> +      setQuantity(parseInt(quantityValue, 10))
Is it important that this statement needs to different to the one in the else.

2022-01-26 12:05 UTC, darrylmorton-digicatapult commented on src/customer/components/CustomerPart.js
> +      setQuantity(parseInt(quantityValue, 10))
this statement represents the value entered by the user when invalid in it's raw form, so could be any character

2022-01-26 12:36 UTC, danielcooperxyz commented on src/customer/components/CustomerPart.js
> +      setCostPerUnit(COST_PER_UNIT_DEFAULT * quantityValue)
It is even possible to simplify this further, only calculating the total cost in the render, if you wanted to. The only downside might be if the total cost is used in multiple places?

2022-01-26 13:18 UTC, mattdean-digicatapult requested changes

2022-01-26 13:18 UTC, mattdean-digicatapult commented on src/customer/components/CustomerPart.js
> +const COST_PER_UNIT_DEFAULT = 1200
This should probably exist in the partsSlice rather than here. Then when those tokens move onchain as receipes it'll be easier

2022-01-26 13:18 UTC, mattdean-digicatapult commented on src/customer/components/CustomerPart.js
> +  const [quantity, setQuantity] = useState(0)
Default `1`? Then it's consistent with total cost

2022-01-26 13:18 UTC, mattdean-digicatapult commented on src/customer/components/CustomerPart.js
> +      setQuantity(parseInt(quantityValue, 10))
I think if you change the default further up this `if else` logic won't be necessaery?

2022-01-26 13:19 UTC, darrylmorton-digicatapult commented on src/customer/components/CustomerPart.js
> +      setQuantity(parseInt(quantityValue, 10))
the input field always obtains the value via the quantity state `value={quantity}`

2022-01-26 15:49 UTC, mattdean-digicatapult commented on src/customer/components/CustomerPart.js
> +  const [totalCost, setTotalCost] = useState(0)
I'm going to comment that this isn't needed as state. You could just define a local variable circa ln 172 that is `const totalCost = price * quantity`.

2022-01-26 16:13 UTC, darrylmorton-digicatapult commented on src/customer/components/CustomerPart.js
> +      setCostPerUnit(COST_PER_UNIT_DEFAULT * quantityValue)
totalCost has now been replaced with a variable instead

2022-01-27 09:38 UTC, mattdean-digicatapult approved these changes

2022-01-27 10:13 UTC, mattdean-digicatapult approved these changes

2022-01-27 10:14 UTC, danielcooperxyz approved these changes

2022-01-27 10:20 UTC, merged