Feat/oem certs view
digicatapult/inteli-demo pull request #32
Opened 2022-02-25 12:44 UTC by jonmattgray

2022-02-25 16:47 UTC, darrylmorton-digicatapult requested changes

2022-02-25 16:47 UTC, darrylmorton-digicatapult commented on src/customer/components/CertificationRow.js
> +          )}
`<img src={file ? tick : pending} className={classes.icon} />`

2022-02-25 16:47 UTC, darrylmorton-digicatapult commented on src/customer/components/CertificationRow.js
> +        {file && (
might be worth combining line 52-58 into this condition block:

changing `{file &&` to `{file ?`
add line 52-58 here without className

the `:` condition just contains
`<Grid
          item
          xs={7}
          className={${classes.greyText} ${classes.rowItem}}
        >
          <Typography>{description}</Typography>
        </Grid>`

2022-02-28 11:28 UTC, jonmattgray commented on src/customer/components/CertificationRow.js
> +          )}
changed, thanks

2022-02-28 12:16 UTC, jonmattgray commented on src/customer/components/CertificationRow.js
> +        {file && (
changed

2022-02-28 12:44 UTC, darrylmorton-digicatapult commented on src/am/components/Orders/CertificationRow.js
> +                  <img src={cloud} className={`${classes.icon}`} />
only className={classes.icon} /> needed

2022-02-28 12:45 UTC, darrylmorton-digicatapult approved these changes

2022-02-28 13:12 UTC, dblane-digicatapult approved these changes

2022-02-28 13:55 UTC, danielcooperxyz approved these changes

2022-02-28 14:34 UTC, merged