User Authentication
digicatapult/inteli-demo pull request #34
Opened 2022-02-28 14:23 UTC by danielcooperxyz

Authentication was previously done using machine to machine authentication. These changes enable users to acces the application and authenticate themselves against Auth0, which is then used for token creation against the blockchain API service.

These changes are only for the basic authentication flow to Auth0 to permit access to the web application and API.

![Screenshot 2022-02-28 at 14 04 41](https://user-images.githubusercontent.com/5233036/155996957-7cd51bfd-09de-493b-9e47-554571be810c.png)
![Screenshot 2022-02-28 at 14 04 48 (2)](https://user-images.githubusercontent.com/5233036/155996967-51d43305-6ced-4075-8e88-098c3ff0878a.png)
![Screenshot 2022-02-28 at 14 12 35](https://user-images.githubusercontent.com/5233036/155997669-f95dcac1-f5bf-4f3e-b002-8fc5749af97f.png)
![Screenshot 2022-02-28 at 14 23 27](https://user-images.githubusercontent.com/5233036/155999314-3d27f2d1-d908-45f3-9a1e-089e6f6aab60.png)

2022-02-28 14:27 UTC, darrylmorton-digicatapult requested changes

2022-02-28 14:27 UTC, darrylmorton-digicatapult commented on src/customer/components/Navigation.js
> +      {isAuthenticated ? (
isAuthenticated &&

2022-02-28 14:27 UTC, darrylmorton-digicatapult commented on src/customer/router/index.js
> +      console.log('Authenticated!')
remove console.log

2022-02-28 14:30 UTC, danielcooperxyz commented on src/customer/router/index.js
> +      console.log('Authenticated!')
removed, thank you

2022-02-28 14:32 UTC, danielcooperxyz commented on src/customer/components/Navigation.js
> +      {isAuthenticated ? (
updated!

2022-02-28 14:34 UTC, n3op2 submitted a review, later dismissed

2022-02-28 14:39 UTC, danielcooperxyz commented on src/utils/url.js
> +  const protocol = window.location.protocol
nice, thanks

2022-02-28 14:40 UTC, danielcooperxyz commented on src/utils/vitalamApi.js
> +      scope: '',
have removed, but i had put it there for explicitness as scopes are part of users permissions, at the moment we do not use them, but don't think we ever will

2022-02-28 15:10 UTC, darrylmorton-digicatapult approved these changes

2022-02-28 15:10 UTC, n3op2 approved these changes

2022-02-28 16:20 UTC, n3op2 approved these changes

2022-02-28 16:46 UTC, n3op2 approved these changes

2022-03-01 10:24 UTC, darrylmorton-digicatapult approved these changes

2022-03-01 10:26 UTC, jonmattgray approved these changes

2022-03-01 10:27 UTC, merged