ConcludePowderTest - new token format
digicatapult/inteli-demo pull request #4
Opened 2022-01-26 08:32 UTC by jonmattgray

2022-01-27 11:20 UTC, darrylmorton-digicatapult requested changes

2022-01-27 11:20 UTC, darrylmorton-digicatapult commented on src/laboratory/components/LabTestDetailsEdit.js
>        reader.onerror = () => console.log('file reading has failed')
console.error

2022-01-27 11:20 UTC, darrylmorton-digicatapult commented on src/laboratory/components/LabTestDetailsEdit.js
> +          ...(files.reportFile
this logic would be better placed inside a reusable function that took args and returned a result

2022-01-27 11:38 UTC, jonmattgray commented on src/laboratory/components/LabTestDetailsEdit.js
> +          ...(files.reportFile
do you mean logic on whether to include the files or the whole object?

2022-01-27 11:59 UTC, jonmattgray commented on src/laboratory/components/LabTestDetailsEdit.js
>        reader.onerror = () => console.log('file reading has failed')
done

2022-01-27 12:06 UTC, jonmattgray commented on src/laboratory/components/LabTestDetailsEdit.js
> -    dispatch(updateLabTest(token))
I've removed this because unlike when we used the `fileData` JSON, the metadata that's sent out is now different from the format we use when we get it back from the API e.g. `type: { type: 'LITERAL', value: 'POWDER_TEST' },` comes back as `type: 'POWDER_TEST'

But it does mean we have to wait for `BlockchainWatcher` to process the new token

2022-01-31 10:34 UTC, mattdean-digicatapult commented on src/laboratory/components/LabTestDetailsEdit.js
> -    dispatch(updateLabTest(token))
Hmmm, I'm not sure I understand this. Surely if it's just reformatting we can match that? Is there information we're missing at this point?

2022-01-31 11:03 UTC, danielcooperxyz reviewed
Good work getting all these changes made.

This is quite a large pr so I'm struggling to consume how much is changing here, but I have made some comments on a couple of things that might help with codebase quality.

2022-01-31 12:35 UTC, jonmattgray commented on src/am/components/Tests/index.js
> +      ({ type, status }) => type === 'POWDER_TEST' && status === 'result'
yes good idea, there'll be lots more of these with the other processes. I'll add it in a similar way to this https://github.com/digicatapult/inteli-demo/blob/main/src/utils/identities.js

2022-02-01 16:43 UTC, mattdean-digicatapult requested changes
I'm going to be honest this is pretty disgustingly huge. I've asked for a couple of console logs to be removed and then I think this should merge. I can't really say that it works but if we don't get this in it'll never be finished. We will find the bugs this probably creates in time

2022-02-01 16:43 UTC, mattdean-digicatapult commented on src/customer/components/DownloadButton.js
> +  console.log(selectedLabTest)
remove `console.log`

2022-02-01 16:43 UTC, mattdean-digicatapult commented on src/customer/components/OrderStatusProgressBar.js
> +  console.log(props)
remove `console.log`

2022-02-01 16:50 UTC, mattdean-digicatapult approved these changes

2022-02-02 08:32 UTC, danielcooperxyz commented on src/am/components/Powders/PowdersDetail.js
> +      metadata: outputData[0],
do we need a lenth validation check for this? also for outputData above too?

2022-02-02 08:34 UTC, danielcooperxyz commented on src/laboratory/components/Request.js
> +        metadata.type === 'PowderTestRequest' &&
missed one here?

2022-02-02 09:39 UTC, jonmattgray commented on src/laboratory/components/Request.js
> +        metadata.type === 'PowderTestRequest' &&
that will be in the next PR, which covers the request side of powder tests

2022-02-02 09:55 UTC, jonmattgray commented on src/am/components/Powders/PowdersDetail.js
> +      metadata: outputData[0],
I'll put that in the next PR too, this file will be changing a lot

2022-02-02 11:58 UTC, merged