Various bug fixes
digicatapult/inteli-demo pull request #50
Opened 2023-02-23 12:18 UTC by mattdean-digicatapult

1. upgrade to latest dscp versions so that we can make demo work offline
2. remove auth so demo works offline
3. fix docker scripts so separate projects are handled correctly
4. fix file handling using data URLs so cached data renders correctly
5. introduce a reset if the lastTokenId decreases so that resets are easier
6. layout bug on am negotiation
7. increase poll frequency and reduce manufacture time to make demo more snappy

2023-03-21 13:27 UTC, dblane-digicatapult requested changes

2023-03-21 13:27 UTC, dblane-digicatapult commented on .github/workflows/release.yml
>            echo "::set-output name=ORG_NAME::$ORG_NAME"
Change set output syntax

2023-03-21 13:27 UTC, dblane-digicatapult commented on .github/workflows/run_tests.yml
>            echo "::set-output name=ORG_NAME::$ORG_NAME"
Change set output syntax

2023-03-21 13:27 UTC, dblane-digicatapult commented on docker/docker-compose-am.yml
> +    image: ghcr.io/digicatapult/dscp-node:v4.5.1
Double check pinned version.

2023-03-21 13:27 UTC, dblane-digicatapult commented on docker/docker-compose-am.yml
> +    image: ghcr.io/digicatapult/dscp-ipfs:v2.9.1
Double check pinned version.

2023-03-21 13:27 UTC, dblane-digicatapult commented on docker/docker-compose-am.yml
> +    image: ghcr.io/digicatapult/dscp-api:v4.8.2
Double check pinned version

2023-03-21 13:27 UTC, dblane-digicatapult commented on scripts/check-version.sh
>      echo "PACKAGE_LOCK_VERSION: $PACKAGE_LOCK_VERSION"
What is this supposed to do?  the syntax is completely wrong.

2023-03-21 13:27 UTC, dblane-digicatapult commented on scripts/check-version.sh
>    echo "##[set-output name=VERSION;]v$CURRENT_VERSION"
Change syntax.

2023-03-21 13:49 UTC, mattdean-digicatapult commented on docker/docker-compose-am.yml
> +    image: ghcr.io/digicatapult/dscp-api:v4.8.2
worked when I gave it at the event

2023-03-21 13:49 UTC, mattdean-digicatapult commented on docker/docker-compose-am.yml
> +    image: ghcr.io/digicatapult/dscp-ipfs:v2.9.1
worked when I gave it at the event

2023-03-21 13:50 UTC, mattdean-digicatapult commented on docker/docker-compose-am.yml
> +    image: ghcr.io/digicatapult/dscp-ipfs:v2.9.1
worked at event

2023-08-02 10:55 UTC, dblane-digicatapult approved these changes

2023-08-02 10:55 UTC, merged