Super rough first Design IN-128
digicatapult/inteli-demo pull request #9
Opened 2022-02-02 11:11 UTC by nitro-marky

This is completely being used as a test bed!

2022-02-14 11:52 UTC, dblane-digicatapult requested changes

2022-02-14 11:52 UTC, dblane-digicatapult commented on src/customer/components/OrderComponents/OrderSummary.js
> +//import VerticalTest from './VerticalTest'
Remove spurious comments

2022-02-14 11:52 UTC, dblane-digicatapult commented on src/customer/components/ProgressBarSelector.js
> +}) */
Remove spurious comments

2022-02-14 11:52 UTC, dblane-digicatapult commented on src/customer/components/ProgressBarSelector.js
> +  //const classes = useStyles()
Remove spurious comment

2022-02-14 11:52 UTC, dblane-digicatapult commented on src/shared/layout.js
> +// TODO refactor
Is this still TODO in this PR or has a ticket been created to deal with this in the future?

If so please remove comment.

2022-02-14 11:52 UTC, dblane-digicatapult commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Why are we now generating a `yarn.lock` file?  Surely we should have updated `package-lock.json` ?

2022-02-14 12:28 UTC, jonmattgray commented on src/customer/components/OrderComponents/verticalTimeline.js
> +  if (type === 'submitted') {
these can be directly compared to the order statuses in the constants file https://github.com/digicatapult/inteli-demo/blob/8202cd4a2c5d349fb64728bdef892534975742b7/src/utils/statuses.js#L6

What used to be grouped under just `type` on tokens is now split into `type` and `status`. For tokens about orders, they all have `type: ORDER` but different statuses such as `submitted` and `accepted` so having the variable named `type` here is a little confusing

2022-02-14 13:04 UTC, jonmattgray commented on src/customer/components/OrderComponents/summaryRow.js
> +  // Split the date so it can be formatted
could use `moment` to reformat? It's also used in a few other places in the repo

2022-02-14 15:05 UTC, nitro-marky commented on src/customer/components/MyOrders.js
> +            key={uniqid()}
I was advised by Darryl to use the `Uniqid` method soo I guess it depends on what the agreed house style is.

2022-02-14 15:52 UTC, darrylmorton-digicatapult requested changes

2022-02-14 15:52 UTC, darrylmorton-digicatapult commented on src/customer/components/MyOrders.js
> +    paddingTop: '20px 20px 20px 0px',
paddingTop only needs '20px' here

2022-02-14 15:52 UTC, darrylmorton-digicatapult commented on src/customer/components/MyOrders.js
> +    // marginRight: 24,
cleanup

2022-02-14 15:52 UTC, darrylmorton-digicatapult commented on src/customer/components/MyOrders.js
> +    /* width: '880px', */
cleanup

2022-02-14 15:52 UTC, darrylmorton-digicatapult commented on src/customer/components/MyOrders.js
> +    /* width: '1280px', */
cleanup

2022-02-14 15:52 UTC, darrylmorton-digicatapult commented on src/customer/components/MyOrders.js
> +            key={uniqid()}
@jonmattgray has a point here, I tend to use the uniqid() probably too much but if the ids are guaranteed to be unique anyway then this is probably overkill. my bad.

2022-02-14 15:52 UTC, darrylmorton-digicatapult commented on src/customer/index.js
> +    //maxWidth: '1350px',
cleanup

2022-02-14 16:05 UTC, darrylmorton-digicatapult commented on package.json
> +    "@emotion/react": "^11.7.1",
Is there anything that the `@emotion/react` and `@emotion/styled` deps are providing that we could leverage material ui to do instead? Feels like more unnecesary deps being introduced?

2022-02-14 17:29 UTC, dblane-digicatapult requested changes

2022-02-14 17:29 UTC, dblane-digicatapult commented on src/customer/components/MyOrders.js
> +  console.log('Params', params.orderId)
Remove debug console.logs

2022-02-15 09:12 UTC, nitro-marky commented on src/customer/components/MyOrders.js
> +  console.log('Params', params.orderId)
Yeah, these were added whilst pairing with Darryl and pushed to branch for him to get access to the latest version. They'll be cleaned up.

2022-02-15 17:01 UTC, dblane-digicatapult submitted a review, later dismissed

2022-02-15 18:09 UTC, jonmattgray commented on src/customer/components/OrderSummary.js
> +      name: name,
some of these can be e.g. `name,` instead of `name: name,`

2022-02-15 18:16 UTC, jonmattgray commented on src/customer/components/VerticalTimeline.js
> +    statusIndex = 4
manufactured and manufacturing should be other way round, manufacturing -> manufactured?

2022-02-15 18:18 UTC, jonmattgray commented on src/customer/index.js
> +    marginBottom: '87px',
these could all go under a single `margin:`

2022-02-16 09:17 UTC, nitro-marky reviewed
Forget this comment!

2022-02-16 17:51 UTC, darrylmorton-digicatapult approved these changes

2022-02-16 17:52 UTC, merged